### ISSUE TITLE
issues with source selection

### ISSUE THREAD

**Issue by via-justa** [Samfox2/homebridge-cec-tv-platform#1]
Existing config
```
{
    "platform": "HomebridgeCECTV",
    "accessories": [
        {
            "name": "Hisense",
            "manufacturer": "Hisense",
            "model": "H43MEC3050",
            "devices": [
                {
                    "1": "Homebridge"
                },
                {
                    "2": "Chromecast"
                },
                {
                    "3": "computer"
                }
            ]
        }
    ]
}
```
1. The config example show to use list instead of map
2. The input selection is translated to `source -1`, I'm not a JS developer but I'll guess the array created starts with 0 instead of 1.
3. Switching the sources from the home app works as long as you not selected for the second time a source that was selected earlier. I guess it's related to the fact all sources are marked as 'on' or there is no selected source marked. I see in the log the requests to change the source are logged but nothing happens 

first and second commands worked but the third and the fourth did not.
```
[24/02/2021, 14:44:03] [HomebridgeCECTV] Switching to HDMI2
[24/02/2021, 14:44:03] [HomebridgeCECTV] Sent CEC command to switch to HDMI2
TRAFFIC: [          697904]     << 1f:82:20:00

waiting for input

TRAFFIC: [          698074]     << 10:9d:10:00

[24/02/2021, 14:44:11] [HomebridgeCECTV] Switching to HDMI1
[24/02/2021, 14:44:11] [HomebridgeCECTV] Sent CEC command to switch to HDMI1
TRAFFIC: [          706261]     << 1f:82:10:00

waiting for input

[24/02/2021, 14:44:20] [HomebridgeCECTV] Switching to HDMI2
[24/02/2021, 14:44:20] [HomebridgeCECTV] Sent CEC command to switch to HDMI2
TRAFFIC: [          715149]     << 1f:82:20:00

waiting for input

[24/02/2021, 14:44:38] [HomebridgeCECTV] Switching to HDMI0
[24/02/2021, 14:44:38] [HomebridgeCECTV] Sent CEC command to switch to HDMI0
TRAFFIC: [          733057]     << 1f:82:00:00

waiting for input

**Comment by Samfox2** [comment]
Hi, thanks for your feedback. I will have a look at it but it is working my tv‘s. I can change input source as often as I want and it is still working.

**Comment by yruah** [comment]
Hello there,
im expierencing the exact same issues, with a simular setup...

**Comment by angyalz** [comment]
Hi! 
I have problems with input select too. I have two defined inputs:
1: RPi
2: Apple TV
When I select first input nothing happens, when select second, the tv switches to first input. 
I tried to change input numbers to 2 and 3, but not solved the problem.

**Comment by angyalz** [comment]
Update: I tried to define a fake 0th input, that works

**Comment by edugrt** [comment]
Same here; I can switch from one source to another one only once. If I switch to a previous source it does nothing. Also, is there any way to include the “antenna” source?

@Samfox2, thanks for this fork!

**Comment by Samfox2** [comment]
You can include whatever source you want, internal tuner should also work. The problem is that I cannot reproduce the error as source switching is working with my setup ( also multiple times).

**Comment by 88fingersmario** [comment]
Logs were showing errors related to setting the input names, resulting in the inputs not being created:
[28/03/2021, 15:49:06] [HomebridgeCECTV] Creating: Sony Bravia
[Sony Bravia@inputSource0@Configured Name] characteristic value expected string and received object
[Sony Bravia@inputSource1@Configured Name] characteristic value expected string and received object
[Sony Bravia@inputSource2@Configured Name] characteristic value expected string and received object
[Sony Bravia@inputSource3@Configured Name] characteristic value expected string and received object
[Sony Bravia@inputSource4@Configured Name] characteristic value expected string and received object

To workaround the problem, I commented out one line in index.js and then used the Home App to set the input names manually:
//                              .setCharacteristic(Characteristic.ConfiguredName, name)

@Samfox2, Note that you may need to remove the accessory and add it back again to see the issue.

**Comment by via-justa** [comment]
No update on the repo for 16 months now. Closing as part of issue list cleanup
