### ISSUE TITLE
Home app Isn’t recognized

### ISSUE THREAD

**Issue by angyalz** [Samfox2/homebridge-cec-tv-platform#2]
Hi!
My problem is that HomeBridge shows at accessories, but Home app isn't shows the device. 
I have no issues at HomeBridge log.

**Comment by angyalz** [comment]
Sorry, it was my mistake, needed to add manually 
But volume is still only at HomeBridge accessories, not in home app

**Comment by Samfox2** [comment]
Yes, thatˋs how it is defined by homekit.
